server {
    listen 8081;
    server_name _;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        add_header Access-Control-Allow-Origin *;
    }

    location ~* \.(js|css)$ {
        root /usr/share/nginx/html;
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
    
    # Healthcheck simple
    location = /health {
        add_header Content-Type text/plain;
        return 200 'ok\n';
    }

    # Proxy 
    location /api/ {
        proxy_pass http://ms-template:8080/api/;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html { root /usr/share/nginx/html; }
}